### ISSUE TITLE
converter is skipping Bezier curves

### ISSUE THREAD

**Issue by rcsavo** [zxfr/strokefont_cyrillic#2]
Hi, 

I used your converter with success, so I decided to redraw a font manually instead of the mess SFEdit produces by itself. But after converting I found that most (but not all) of the characters have one or two Bezier curves missing. This problem is not apparent, when a character has like 30 vector points, since the difference is so miniscule.

As an example: 

![kép](https://user-images.githubusercontent.com/57327262/68089891-c6b2ae80-fe6d-11e9-9b5e-c4dc9a2fbbab.png)

And this is what I get:

![kép](https://user-images.githubusercontent.com/57327262/68089922-1b562980-fe6e-11e9-8f59-caee8aca185d.png)

Could you please take a look to it? If needed, I can send you the sf2 file in question.

Thank you very much!

**Comment by zxfr** [comment]
Hi! Obviously the missing curves are cubic Bézier curves, but the converter has quadratic Bézier curves support only. In fact, it reads all 6 parameters of cubic Bézier curves, but uses only four of them - I had no suitable font to test the case that time. If you send the SF2 - it could help a lot.

**Comment by rcsavo** [comment]
Hi zxfr!

Thank you very much for getting back to me.

Please find the files here: https://drive.google.com/open?id=1WWlY0AfA-0tATtkpzdib82Cb8axHaawE

BTW, if you take a look at the preview svg, you can see, that the converter has skipped the space character at the beginning. When this happens, the advance width of the characters is off by 1 character (for example the letter B gets the width of letter A) in the *.py file. I couldn't find out, why and when this happens, but that is something I could easily fix by myself.

**Comment by zxfr** [comment]
Hi! The task is not that simple as I expected. There is no any documentation on the file format, so I've spent a while to play with the Bézier curve params obtained from the font file, trying to map them to various SVG path components. I had a success with perfect rendering of 'm', but that impacted/corrupted a lot of other glyphs... Also letters like 'o' are defined with something like cyclic Bézier curve: there are four segments and every segment curvature depends on previous segment curvature. So it is not clear where to start and how to define starting conditions for the first segment... I need to read a bit more about Bézier curves. Hopefully if I have time I'll address the topic over the weekend.

**Comment by rcsavo** [comment]
Hi zxfr!

I truly appreciate the time and effort you put into solving this matter.

**Comment by zxfr** [comment]
Hi! It has taken more than expected, but it seems I've finally found a solution. Please give a try to the updated version

**Comment by rcsavo** [comment]
Hi zxfr!

I gave it a try and now it works perfectly! Beautiful, clean curves all the way! I am so glad, you could fix this, thank you so much for your effort!

**Comment by zxfr** [comment]
:-)
